spring.application.name=learning-spring
spring.profiles.active=dev
app.sms.enabled=true
number.format=###.## RON
app.payment.fee-percent=2.5
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true